### PR TITLE
Fuel the hype machine

### PR DESCRIPTION
**Pull request by wvu-r7**
Or don't.

### CODE REVIEW

**Comment by bcoles** [comment]
This seems like a bad idea, given that some logos and soundtracks are hosted over clear text HTTP, or use an [invalid cert](https://heartbleed.com/heartbleed.png).

**Comment by bcoles** [comment]
Should `ENV` have been `Rex::Compat.getenv` instead?

**Comment by wvu-r7** [comment]
I was literally just thinking that after #10304. I think it's fine unless we're serious about Windows support. There have been talks about dropping it, but it gets a lot of downloads...

**Comment by wvu-r7** [comment]
I'd switch it for now, though.

**Comment by wvu-r7** [comment]
Honestly, I just forgot about that `Rex::Compat` method, heh. There are others we should be using more consistently, too.

**Pull request merged**
